# Make sure to check the documentation at https://goreleaser.com, https://goreleaser.com/customization/
project_name: gossh
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
  -
    main: ./cmd/gossh/main.go
    hooks:
      post: ./upx.sh gossh
    goarch:
      - amd64
env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
